### ISSUE TITLE
No meter bar activity...

### ISSUE THREAD

**Issue by htartisan** [ffAudio/ff_meters#17]
After some effort, I got this control/component to build as part of my application (though I still get warnings).

Everything looks good, and I did my best to follow the code example below, however... I do NOT get any activity on the meters.

Is there something that needs to be initialized, other than what is shown in the code example below? 

Is there some example application that uses this that I can download/build?

**Comment by TheOnlyJoey** [comment]
Having the same issue using the Outline class, it seems to only update once (on first frame) and then never updates again... running JUCE 6.0.4 on Linux

EDIT: Seems just to be the example code not really keeping track of drawing, threads etc. forcing redraw works.

**Comment by ffAudio** [comment]
Indeed, the OutlineBuffer is just a drawing class. It is the responsibility of the Component using the OutlineBuffer to implement a timerCallback() to redraw according to the needs of the use case.

Closing this now.
