### ISSUE TITLE
Does not compile on MSVC

### ISSUE THREAD

**Issue by tobanteAudio** [ffAudio/ff_meters#9]
The pragma does not compile on MSVC:
```cpp
#if FF_AUDIO_ALLOW_ALLOCATIONS_IN_MEASURE_BLOCK
#warning The use of levels.resize() is not realtime safe. Please call resize from the message thread and set this config setting to 0 via Projucer.
            levels.resize (size_t (numChannels));
#endif
```

**Comment by ffAudio** [comment]
Thank you for the heads up. I will change that to use "pragma message" on windows.
However, it is strongly advised to switch that config option off, in which case the whole block is ignored anyway.
It is just to keep old code working, but that old method was never 100% realtime safe.

**Comment by ffAudio** [comment]
The whole block is now removed. Thanks for the feedback.
